const COOKIE_CONTROLLER_URL:string = import.meta.env.VITE_COOKIE_CONTROLLER;
const TOPICS_CONTROLLER_URL:string = import.meta.env.VITE_TOPICS_CONTROLLER;
const USERS_CONTROLLER_URL:string = import.meta.env.VITE_USERS_CONTROLLER;
const THREADS_CONTROLLER_URL:string = import.meta.env.VITE_THREADS_CONTROLLER;
const POSTS_CONTROLLER_URL:string = import.meta.env.VITE_POST_CONTROLLER;


export const REGISTER_REQUEST = `${COOKIE_CONTROLLER_URL}/register`;
export const LOGIN_REQUEST = `${COOKIE_CONTROLLER_URL}/login`;
export const TOPICS_REQUEST = TOPICS_CONTROLLER_URL;
export const USERS_PROFILE_REQUEST = USERS_CONTROLLER_URL;
export const THREADS_REQUEST = THREADS_CONTROLLER_URL;
export const POST_REQUEST = POSTS_CONTROLLER_URL;

export enum HTTP_CODES {
    OK = 200,
    BAD_REQUEST = 400,
    NO_CONTENT = 204,
    UNAUTHORIZED = 401,
}
